inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  RubyInterpreters:
    - ruby
    - macruby
    - rake
    - jruby
    - rbx
  # Include common Ruby source files.
  Exclude:
      - bin/*
      - db/schema.rb
      - db/migrate/*
      - config/initializers/*
  NewCops: enable
  TargetRubyVersion: 2.7
Layout/LineLength:
  Max: 150
  Exclude:
Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be a Fixnum or
  # a Float.
  Max: 32
  Exclude:
Metrics/BlockLength:
  Max: 38
  Exclude:
Metrics/ClassLength:
  Max: 130
  Exclude:
Metrics/CyclomaticComplexity:
  Max: 12
  Exclude:
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20
  Exclude:
Metrics/ModuleLength:
  Max: 120
  Exclude:
Metrics/PerceivedComplexity:
  Max: 12
  Exclude: